name: My node app workflow
on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Clean install dependencies and build
        run: |
          npm install
          npm run build
        shell: powershell
        working-directory: ./app

      - name: Run app script
        run: |
          console.log('Starting application...');
          console.log('GITHUB_WORKSPACE:', process.env.GITHUB_WORKSPACE);
          require(process.env.GITHUB_WORKSPACE + '/app/index.js');
          console.log('Application executed successfully!');
        shell: node {0}
        working-directory: ./app
