name: My node app workflow
on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os_version: [ubuntu-latest, macos-latest]
        node_version: [16, 18, 20]
    
    name: Run build tests on ${{ matrix.os_version }} with node ${{ matrix.node_version }}
    runs-on: ${{ matrix.os_version }}

    steps:
      - name: Show matrix variable
        run: |
          echo "Running matrix:"
          echo "$(echo '${{ toJson(matrix) }}')"
          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Show environment variables
        run: |
          echo "Environment variables:"
          echo "$(echo '${{ toJson(env)}}')"

      - name: Show environment variables
        run: foreach $k (sort keys %ENV) { print "$k=$ENV{$k}\n"; }
        shell: perl {0}

      - name: Clean install dependencies and build
        run: |
          npm install
          npm run build
        shell: bash
        working-directory: ./app

      - name: Run app script
        run: |
          console.log('Starting application...');
          console.log('GITHUB_WORKSPACE:', process.env.GITHUB_WORKSPACE);
          require(process.env.GITHUB_WORKSPACE + '/app/index.js');
          console.log('Application executed successfully!');
        shell: node {0}
        working-directory: ./app
