name: Debug Message Demo
on:
  workflow_dispatch:
jobs:
  debug-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        run: |
          echo "::debug::Starting environment setup"